# Generated by Django 5.2.10 on 2026-02-08 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('tc_no', models.CharField(blank=True, max_length=11, null=True)),
                ('giris_tarihi', models.DateField(blank=True, null=True)),
                ('cikis_tarihi', models.DateField(blank=True, null=True)),
                ('departman', models.CharField(blank=True, max_length=100, null=True)),
                ('pozisyon', models.CharField(blank=True, max_length=100, null=True)),
                ('aylik_brut_ucret', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgk_tipi', models.CharField(default='01', max_length=10)),
                ('kanun_kodu', models.CharField(default='00000', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisanlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çalışan',
                'verbose_name_plural': 'Çalışanlar',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.CreateModel(
            name='Tazminat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_tarihi', models.DateField()),
                ('cikis_tarihi', models.DateField()),
                ('kidem_disi_sure', models.IntegerField(default=0)),
                ('aylik_brut_ucret', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aylik_brut_ek_ucret', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yillik_brut_ikramiye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kumulatif_gv_matrahi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ihbar_tazminati', models.BooleanField(default=True)),
                ('ihbar_gelir_vergisi', models.BooleanField(default=True)),
                ('ihbar_damga_vergisi', models.BooleanField(default=True)),
                ('kidem_damga_vergisi', models.BooleanField(default=True)),
                ('hesaplama_sonuc', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tazminatlar', to='bordro_app.calisan')),
            ],
            options={
                'verbose_name': 'Tazminat',
                'verbose_name_plural': 'Tazminatlar',
            },
        ),
        migrations.CreateModel(
            name='AylikBordro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordro_ay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('bordro_yil', models.IntegerField()),
                ('aylik_temel_ucret', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ucret_tipi', models.CharField(choices=[('brut', 'Brüt'), ('net', 'Net')], default='brut', max_length=10)),
                ('gelir_vergisi', models.BooleanField(default=True)),
                ('damga_vergisi', models.BooleanField(default=True)),
                ('engellilik_durumu', models.CharField(choices=[('normal', 'Normal'), ('1_derece', '1. Derece'), ('2_derece', '2. Derece'), ('3_derece', '3. Derece')], default='normal', max_length=20)),
                ('yillik_gv_matrahi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yillik_asg_ucret_gv_matrahi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gun_sayisi_tipi', models.CharField(default='takvim', max_length=20)),
                ('calisilan_gun', models.IntegerField(default=30)),
                ('eksik_saat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sgk_tipi', models.CharField(default='01', max_length=100)),
                ('kanun_no', models.CharField(default='00000', max_length=20)),
                ('hazine_yardimi', models.BooleanField(default=True)),
                ('bes', models.BooleanField(default=False)),
                ('devir_matrah_2ay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devir_matrah_1ay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saglik_sig_isci', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saglik_sig_isveren', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hayat_sig_isci', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hayat_sig_isveren', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fm01_saat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fm02_saat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fm03_saat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hesaplama_sonuc', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bordrolar', to='bordro_app.calisan')),
            ],
            options={
                'verbose_name': 'Aylık Bordro',
                'verbose_name_plural': 'Aylık Bordrolar',
                'unique_together': {('calisan', 'bordro_yil', 'bordro_ay')},
            },
        ),
        migrations.CreateModel(
            name='YillikBordro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordro_yili', models.IntegerField()),
                ('sgk_tipi', models.CharField(default='01', max_length=10)),
                ('kanun_kodu', models.CharField(default='00000', max_length=10)),
                ('bes_aktif', models.BooleanField(default=False)),
                ('engellilik_derecesi', models.CharField(choices=[('normal', 'Normal'), ('1_derece', '1. Derece'), ('2_derece', '2. Derece'), ('3_derece', '3. Derece')], default='normal', max_length=20)),
                ('takvim_esasli', models.BooleanField(default=True)),
                ('aylik_veriler', models.JSONField()),
                ('aylik_sonuclar', models.JSONField(blank=True, null=True)),
                ('yillik_ozet', models.JSONField(blank=True, null=True)),
                ('toplam_brut', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('toplam_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('toplam_gv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('toplam_sgk_isci', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('toplam_isveren_maliyeti', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yillik_bordrolar', to='bordro_app.calisan')),
            ],
            options={
                'verbose_name': 'Yıllık Bordro',
                'verbose_name_plural': 'Yıllık Bordrolar',
                'unique_together': {('calisan', 'bordro_yili')},
            },
        ),
    ]
