# Generated by Django 5.2.10 on 2026-02-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordro_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calisan',
            name='aylik_brut_ucret',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='cikis_tarihi',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='departman',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='giris_tarihi',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='kanun_kodu',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='pozisyon',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='sgk_tipi',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='tc_no',
        ),
        migrations.RemoveField(
            model_name='calisan',
            name='updated_at',
        ),
    ]
