# Generated by Django 5.2.10 on 2026-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordro_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yillikbordro',
            name='toplam_gv_matrahi',
        ),
        migrations.RemoveField(
            model_name='yillikbordro',
            name='toplam_sgk_matrahi',
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='aylik_sonuclar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='bes_aktif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='engellilik_derecesi',
            field=models.CharField(choices=[('normal', 'Normal'), ('1_derece', '1. Derece'), ('2_derece', '2. Derece'), ('3_derece', '3. Derece')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='kanun_kodu',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='sgk_tipi',
            field=models.CharField(default='01', max_length=10),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='takvim_esasli',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='toplam_brut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='toplam_gv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='toplam_isveren_maliyeti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='toplam_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='toplam_sgk_isci',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='yillik_ozet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
