# Generated by Django 5.2.10 on 2026-02-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordro_app', '0002_remove_yillikbordro_toplam_gv_matrahi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tazminat',
            name='kumulatif_gv_matrahi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='tazminat',
            name='calisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tazminatlar', to='bordro_app.calisan'),
        ),
    ]
