# Generated by Django 5.2.10 on 2026-02-20 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordro_app', '0002_remove_calisan_aylik_brut_ucret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aylikbordro',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='yillikbordro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aylikbordro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aylik_bordrolar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tazminat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tazminatlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yillikbordro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yillik_bordrolar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tazminat',
            name='calisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tazminatlar_calisan', to='bordro_app.calisan'),
        ),
        migrations.AlterField(
            model_name='yillikbordro',
            name='calisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yillik_bordrolar_calisan', to='bordro_app.calisan'),
        ),
    ]
