# Generated by Django 5.2.10 on 2026-02-20 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordro_app', '0003_alter_aylikbordro_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aylikbordro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aylik_bordrolar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tazminat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tazminatlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yillikbordro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yillik_bordrolar', to=settings.AUTH_USER_MODEL),
        ),
    ]
