ASGARI_UCRET_BRUT = 33030.00
ASGARI_UCRET_GUNLUK = 1101.00
ASGARI_UCRET_SAATLIK = 146.80

AYLIK_GUN = 30
AYLIK_SAAT = 225
HAFTALIK_SAAT = 45

SGK_ISCI_ORANI = 14.00
SGK_ISVEREN_ORANI = 21.75
SGK_ISVEREN_TEHLIKELI = 20.50
SGK_KVSK_ORANI = 2.25
ISSIZLIK_ISCI_ORANI = 1.00
ISSIZLIK_ISVEREN_ORANI = 2.00
BES_ORANI = 3.00
HAZINE_YARDIMI_ORANI = 5.00

SGK_TABAN = ASGARI_UCRET_BRUT
SGK_TAVAN_KATSAYI = 9
SGK_TAVAN = ASGARI_UCRET_BRUT * SGK_TAVAN_KATSAYI

GELIR_VERGISI_DILIMLERI = [
    (190000.00, 15.00),
    (400000.00, 20.00),
    (1500000.00, 27.00),
    (5300000.00, 35.00),
    (None, 40.00),
]
DAMGA_VERGISI_ORANI = 0.759

SAGLIK_SIGORTA_INDIRIM_ORANI = 15.00
HAYAT_SIGORTA_INDIRIM_ORANI = 50.00
YILLIK_SIGORTA_INDIRIM_LIMIT = ASGARI_UCRET_BRUT * 12

FAZLA_MESAI_ORANLARI = {
    'FM01': 50.00,
    'FM02': 100.00,
    'FM03': 200.00,
}
ENGELLILIK_INDIRIMI = {
    '1': 12000.00,
    '2': 7000.00,
    '3': 3000.00,
}
AYLAR = {
    1: 'Ocak',
    2: 'Şubat',
    3: 'Mart',
    4: 'Nisan',
    5: 'Mayıs',
    6: 'Haziran',
    7: 'Temmuz',
    8: 'Ağustos',
    9: 'Eylül',
    10: 'Ekim',
    11: 'Kasım',
    12: 'Aralık',
}

SGK_TIPLERI = {
    '1': {
        'ad': 'Hizmet Akdi ile Tüm Sigorta Kollarına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 19.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 2.00,
    },
    '2': {
        'ad': 'Sosyal Güvenlik Destek Primine Tabi Çalışanlar (Emekliler)',
        'kvsk': 2.25,
        'sgk_isci': 7.50,
        'sgk_isveren': 22.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '4': {
        'ad': 'Yer Altında Sürekli Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 21.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '5': {
        'ad': 'Yer Altında Gruplu (Münavebeli) Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 21.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '6': {
        'ad': 'Yer Üstü Gruplu Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 21.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '7': {
        'ad': '3308 Sayılı Kanunda Belirtilen Aday Çırak, Çırak ve İşletmelerde Eğitim Gören Öğrenciler',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 1.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '12': {
        'ad': 'Geçici 20. Maddeye Tabi Olanlar (Sandık, Oda, Borsa ve Birlik)',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 0.00,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 0.00,
    },
    '13': {
        'ad': 'Tüm Sigorta Kollarına Tabi Olup İşsizlik Sigortası Primi Kesilmeyenler',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 19.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 2.00,
    },
    '14': {
        'ad': 'Libya\'da Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 9.00,
        'sgk_isveren': 11.00,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 0.00,
    },
    '19': {
        'ad': 'Ceza İnfaz Kurumları ile Tutukevleri Bünyesinde Oluşturulan Tesis Atölye ve Benzeri Ünitelerde Çalıştırılan Hükümlü ve Tutuklular',
        'kvsk': 2.25,
        'sgk_isci': 0.00,
        'sgk_isveren': 0.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '20': {
        'ad': 'İstisna Akdine İstinaden Almanya\'ya Götürülen Türk İşçiler',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 19.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 0.00,
    },
    '21': {
        'ad': 'Türk İşverenler Tarafından Sosyal Güvenlik Sözleşmesi İmzalanmamış Ülkelere Götürülerek Çalıştırılan Türk İşçileri',
        'kvsk': 2.25,
        'sgk_isci': 5.00,
        'sgk_isveren': 7.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '22': {
        'ad': 'Meslek Liselerinde Okumakta İken veya Yüksek Öğrenimleri Sırasında Staja Tabi Tutulan Öğrenciler ile Üniversitelerde Kısmi Zamanlı Çalıştırılan Öğrenciler',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 1.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '23': {
        'ad': 'Harp Malulleri ile 3713 ve 2330 Sayılı Kanunlara Göre Vazife Malullüğü Aylığı Alanlardan Kısa Vadeli Sigorta Kollarına Tabi Olanlar',
        'kvsk': 2.25,
        'sgk_isci': 0.00,
        'sgk_isveren': 0.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '24': {
        'ad': 'Harp Malulleri ile 3713 ve 2330 Sayılı Kanunlara Göre Vazife Malullüğü Aylığı Alanlardan Kısa ve Uzun Vadeli Sigorta Kollarına Tabi Olanlar',
        'kvsk': 2.25,
        'sgk_isci': 9.00,
        'sgk_isveren': 11.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 4.00,
    },
    '25': {
        'ad': 'Türkiye İş Kurumu Tarafından Düzenlenen Eğitimlere Katılan Kursiyerler',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 1.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '28': {
        'ad': '4046 Sayılı Kanunun 21 inci Maddesi Kapsamında İş Kaybı Tazminatı Alanlar',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 32.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '29': {
        'ad': 'Tüm Sigorta Kollarına Tabi Çalışıp 60 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 19.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '30': {
        'ad': 'İşsizlik Sigortası Hariç 60 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 19.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 4.00,
    },
    '31': {
        'ad': 'Harp Malülleri ile Vazife Malullüğü Aylığı Alanlardan Kısa ve Uzun Vadeli Sigorta Kollarına Tabi Olup 60 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 9.00,
        'sgk_isveren': 12.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '32': {
        'ad': 'Tüm Sigorta Kollarına Tabi Çalışıp 90 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 20.00,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '33': {
        'ad': 'İşsizlik Sigortası Hariç 90 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 20.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 4.00,
    },
    '34': {
        'ad': 'Harp Malülleri ile Vazife Malullüğü Aylığı Alanlardan Kısa ve Uzun Vadeli Sigorta Kollarına Tabi Olup 90 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 9.00,
        'sgk_isveren': 12.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 4.00,
    },
    '35': {
        'ad': 'Tüm Sigorta Kollarına Tabi Çalışıp 180 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 21.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '36': {
        'ad': 'İşsizlik Sigortası Hariç 180 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 14.00,
        'sgk_isveren': 21.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 4.00,
    },
    '37': {
        'ad': 'Harp Malülleri ile Vazife Malullüğü Aylığı Alanlardan Kısa ve Uzun Vadeli Sigorta Kollarına Tabi Olup 180 Gün Fiili Hizmet Süresi Zammına Tabi Çalışanlar',
        'kvsk': 2.25,
        'sgk_isci': 9.00,
        'sgk_isveren': 14.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 4.00,
    },
    '39': {
        'ad': 'Birleşik Krallıkta İkamet Edenler ve İsviçre Vatandaşı Olanlardan Uzun Vadeli Sigorta Kolunun Uygulanmasını Talep Etmeyenler',
        'kvsk': 2.25,
        'sgk_isci': 5.00,
        'sgk_isveren': 7.50,
        'issizlik_isci': 1.00,
        'issizlik_isveren': 2.00,
        'hazine_yardimi': 4.00,
    },
    '41': {
        'ad': 'Kamu İdarelerinde İş Akdi Askıda Olanlar',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 12.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '90': {
        'ad': 'İtibari Hizmet Süresine Tabi Çalışanlar',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 20.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '91': {
        'ad': '60 Gün Fiili Hizmet Süresi Zammına Tabi Olanlardan İtibari Hizmet Süresine Tabi Olarak Çalışanlar',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 21.00,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
    '92': {
        'ad': '90 Gün Fiili Hizmet Süresi Zammına Tabi Olanlardan İtibari Hizmet Süresine Tabi Olarak Çalışanlar',
        'kvsk': 0.00,
        'sgk_isci': 0.00,
        'sgk_isveren': 21.50,
        'issizlik_isci': 0.00,
        'issizlik_isveren': 0.00,
        'hazine_yardimi': 0.00,
    },
}
VARSAYILAN_SGK_TIPI = '1'
SGK_KANUNLARI = {
    '05746': {
        'ad': 'Araştırma Geliştirme Faaliyetlerinin Desteklenmesi Hakkındaki Kanun',
        'aciklama': 'PEK üzerinden SGK işveren hissesinin yarısı',
        'matrah_tipi': 'pek',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 50,
        'gunluk_tutar': 0,
        'belgeler': ['2008-085', '2009-021'],
    },
    '05921': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (4447 nolu kanunun geçici 9. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
    '06111': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (4447 nolu kanunun geçici 10. maddesi)',
        'aciklama': 'PEK üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
    '06486': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası (5510 nolu kanunun 81 maddesinin 1. fıkrası)',
        'aciklama': 'PEK üzerinden %5',
        'matrah_tipi': 'pek',
        'kapsam': ['ozel_oran'],
        'indirim_orani': 5,
        'gunluk_tutar': 0,
        'belgeler': ['2013-030'],
    },
    '06645': {
        'ad': '4447 Sayılı Kanunun Geçici 15. maddesinde Öngörülen Sigorta Primi Teşviği',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2016-001'],
    },
    '14447': {
        'ad': 'Genç İstihdam Teşviği 1. Sene - %100 (4447 nolu kanunun geçici 7. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
    '14857': {
        'ad': 'Özürlü Personel İşveren Teşviği Kanunu (Kontenjan Dahili)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2008-077'],
    },
    '15921': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (4447 nolu kanunun 50. maddesinin 5. fıkrası)',
        'aciklama': 'PEK alt sınırı üzerinden KVSK\'nin %1\'i ile SGK işçi ve işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren', 'sgk_isci', 'kvsk_kismi'],
        'isveren_orani': 18.5,
        'indirim_orani': 100,
        'kvsk_orani': 1,
        'gunluk_tutar': 0,
        'belgeler': ['2009-149'],
    },
    '16322': {
        'ad': 'Yatırımlarda Devlet Yardımları Hakkında Karar Gereği Uygulanan Teşvik (6322 sayılı kanun)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2012-030'],
    },
    '24447': {
        'ad': 'Genç İstihdam Teşviği 5. Sene - %20 (4447 nolu kanunun geçici 7. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin %20\'si',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 20,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
    '25225': {
        'ad': 'Kültür Yatırımları Kapsamında Sağlanan Teşvik (5225 nolu kanunun 5. maddesi)',
        'aciklama': 'PEK üzerinden SGK işveren hissesinin yarısı',
        'matrah_tipi': 'pek',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 50,
        'gunluk_tutar': 0,
        'belgeler': ['2010-109'],
    },
    '25510': {
        'ad': 'Yatırımlarda Devlet Yardımları Hakkında Karar Gereği Uygulanan Teşvik (5510 nolu kanunun Ek 2. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2011-054'],
    },
    '26322': {
        'ad': 'Yatırımlarda Devlet Yardımları Hakkında Karar Gereği Uygulanan Teşvik (6322 sayılı kanun)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işçi ve işveren hissesinin tamamı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren', 'sgk_isci'],
        'indirim_orani': 100,
        'gunluk_tutar': 0,
        'belgeler': ['2012-030'],
    },
    '44447': {
        'ad': 'Genç İstihdam Teşviği 4. Sene - %40 (4447 nolu kanunun geçici 7. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin %40\'ı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 40,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
    '46486': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (I.Bölge) (5510 nolu kanunun 81 maddesinin 2. fıkrası)',
        'aciklama': 'PEK alt sınırı üzerinden %6',
        'matrah_tipi': 'pek',
        'kapsam': ['ozel_oran'],
        'indirim_orani': 6,
        'gunluk_tutar': 0,
        'belgeler': ['2013-030', '2016-008'],
    },
    '54857': {
        'ad': 'Özürlü Personel İşveren Teşviği Kanunu (Kontenjan Fazlası)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin yarısı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 50,
        'gunluk_tutar': 0,
        'belgeler': ['2008-077'],
    },
    '55225': {
        'ad': 'Kültür Girişimleri Kapsamında Sağlanan Teşvik (5225 nolu kanunun 5. maddesi)',
        'aciklama': 'PEK üzerinden SGK işveren hissesinin %25\'i',
        'matrah_tipi': 'pek',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 25,
        'gunluk_tutar': 0,
        'belgeler': ['2010-109'],
    },
    '56486': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (II.Bölge) (5510 nolu kanunun 81 maddesinin 2. fıkrası)',
        'aciklama': 'PEK alt sınırı üzerinden %6',
        'matrah_tipi': 'pek',
        'kapsam': ['ozel_oran'],
        'indirim_orani': 6,
        'gunluk_tutar': 0,
        'belgeler': ['2013-030', '2016-008'],
    },
    '64447': {
        'ad': 'Genç İstihdam Teşviği 3. Sene - %60 (4447 nolu kanunun geçici 7. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin %60\'ı',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 60,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
    '66486': {
        'ad': 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (III.Bölge) (5510 nolu kanunun 81 maddesinin 2. fıkrası)',
        'aciklama': 'PEK alt sınırı üzerinden %6',
        'matrah_tipi': 'pek',
        'kapsam': ['ozel_oran'],
        'indirim_orani': 6,
        'gunluk_tutar': 0,
        'belgeler': ['2013-030', '2016-008'],
    },
    '84447': {
        'ad': 'Genç İstihdam Teşviği 2. Sene - %80 (4447 nolu kanunun geçici 7. maddesi)',
        'aciklama': 'PEK alt sınırı üzerinden SGK işveren hissesinin %80\'i',
        'matrah_tipi': 'pek_alt_sinir',
        'kapsam': ['sgk_isveren'],
        'indirim_orani': 80,
        'gunluk_tutar': 0,
        'belgeler': ['2011-045'],
    },
}

VARSAYILAN_KANUN = None

def get_sgk_oranlari(sgk_tipi='1'):
    if sgk_tipi not in SGK_TIPLERI:
        sgk_tipi = VARSAYILAN_SGK_TIPI

    return SGK_TIPLERI[sgk_tipi]


def get_kanun_bilgisi(kanun_kodu):
    if kanun_kodu is None:
        return None

    kanun_kodu = str(kanun_kodu).zfill(5)
    return SGK_KANUNLARI.get(kanun_kodu)